# Generated by Django 2.1.5 on 2019-01-11 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, unique=True)),
                ('userkname', models.CharField(max_length=10)),
                ('s_gender', models.BooleanField(default=1)),
                ('userage', models.IntegerField(max_length=4)),
                ('password', models.CharField(max_length=150)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
