# Generated by Django 2.1.5 on 2019-01-12 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_back', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=10, unique=True)),
                ('b_name', models.CharField(max_length=10)),
                ('f_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='father', to='blog_back.Category')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='CategoryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_words', models.CharField(max_length=20, null=True)),
                ('catinfo', models.CharField(max_length=255, null=True)),
                ('cat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog_back.Category')),
            ],
            options={
                'db_table': 'catinfo',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='userage',
            field=models.IntegerField(max_length=3),
        ),
    ]
