# Generated by Django 2.1.5 on 2019-01-14 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_back', '0002_auto_20190112_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=500)),
                ('key_words', models.CharField(max_length=30, null=True)),
                ('discribe', models.CharField(max_length=30, null=True)),
                ('tage', models.CharField(max_length=30, null=True)),
                ('icon', models.ImageField(null=True, upload_to='uplod', verbose_name='文章图片')),
                ('c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='blog_back.Category')),
            ],
            options={
                'db_table': 'article',
            },
        ),
    ]
